apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: khy-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - http:
        paths:
          - path: /nginxTest
            pathType: Prefix
            backend:
              service:
                name: khy-nginx-nlb
                port:
                  number: 80
          - path: /apacheTest
            pathType: Prefix
            backend:
              service:
                name: khy-apache-nlb
                port:
                  number: 80