Name:                     istio-ingressgateway
Namespace:                istio-system
Labels:                   app=istio-ingressgateway
  install.operator.istio.io/owning-resource=unknown
  install.operator.istio.io/owning-resource-namespace=istio-system
  istio=ingressgateway
  istio.io/rev=default
  operator.istio.io/component=IngressGateways
  operator.istio.io/managed=Reconcile
  operator.istio.io/version=1.14.1
  release=istio
Annotations:              <none>
Selector:                 app=istio-ingressgateway,istio=ingressgateway
Type:                     LoadBalancer
IP Family Policy:         SingleStack
IP Families:              IPv4
IP:                       10.100.202.19
IPs:                      10.100.202.19
LoadBalancer Ingress:     aa39194acbbac423faf85ed49b3b67c4-640780309.ap-northeast-2.elb.amazonaws.com

Port:                     status-port  15021/TCP # health check
TargetPort:               15021/TCP # lb port
NodePort:                 status-port  30753/TCP
Endpoints:                192.168.9.17:15021 # istio-ingressgateway pod 의 ip주소

Port:                     http2  80/TCP
TargetPort:               8080/TCP
NodePort:                 http2  31952/TCP
Endpoints:                192.168.9.17:8080

Port:                     https  443/TCP # webhooks service port
TargetPort:               8443/TCP
NodePort:                 https  30186/TCP
Endpoints:                192.168.9.17:8443

Port:                     tcp  31400/TCP
TargetPort:               31400/TCP
NodePort:                 tcp  32269/TCP
Endpoints:                192.168.9.17:31400

Port:                     tls  15443/TCP
TargetPort:               15443/TCP
NodePort:                 tls  30312/TCP
Endpoints:                192.168.9.17:15443

Session Affinity:         None
External Traffic Policy:  Cluster
Events:                   <none>